; MOV THE DATA FROM SOURCE TO DESTINATION

.DATA
DATA1 DB 'ABCD123456' ;SOURCE
DATA2 DB ? ;DESTINATION 


.CODE
START:

    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    CLD ;CLEAR DIRECTIONAL FLAG FOR AUTO INCREMENT
    MOV SI, OFFSET DATA1  ;SOURCE POINTER
    MOV DI, OFFSET DATA2  ;DESTINATION POINTER
    MOV CX, 10
    REP MOVSB
END START