;QUESTION 1
.DATA
NUM1 DB 05H
NUM2 DB 07H
NUM3 DW 1234H
NUM4 DW 5678H
SUM1 DB ?
SUM2 DW ? 

;---------------------

.CODE
START :
    MOV AX, DATA
    MOV DS, AX ;INITIALIZE DATA SEGMENT
    XOR AX, AX ;RESET AX/MOV AX, 0000H
    MOV AL, NUM1 ;LOADING NUM1 TO THE AL REGISTER
    MOV BL, NUM2 ;LOADING NUM2 TO THE BL REGISTER
    ADD AL, BL
    MOV SUM1, AL ;STORING THE RESULT IN MEMORY
    
    MOV CX, NUM3
    ADD CX, NUM4
    MOV SUM2, CX ;STORING THE RESULT IN MEMORY 
    MOV AH, 4CH ; END OF PROGRAM
    
    INT 21H         
    
END START                       

; RESULT:
; SUM1 -> 4CH
; SUM2 -> 68ACH
    