;Q3. Write a program to find out the sum of the digits of a 16-bit number.

.DATA
NUMBER DW 12345
RES DW ?

.CODE
START:
    MOV AX, DATA
    MOV DS, AX
    XOR AX, AX
    MOV AX, NUMBER
    MOV BX, 10
    XOR CX, CX ;SETTING CL U TO STORE THE RESULT
    
    SumOfDigits: ;LABEL OF THE LOOP
    XOR DX, DX ;CLEAR UP THE DX REDISTER TO STORE THE REMAINDER
    DIV BX ;DIVIDING AX WITH BX WHERE THE QUOTIENT IN AX AND THE REMAINDER IN DX
    ADD CX, DX ;STORING THE REMAINDER IN CX
    MOV RES, CX ;RESULT LOADING IN MEMORY
    
    CMP AX, 0;IF THE QUOTIENT IS 0
    JNZ SumOfDigits
    
    INT 21H
    
    
END START