;Q4. Write a program to find out a minimum of two numbers.  

.DATA
NUMBER1 DB 12
NUMBER2 DB 14
RES DB ?

.CODE
START:
    MOV AX, DATA
    MOV DS, AX
    XOR AX, AX
    
    MOV AL, NUMBER1
    MOV BL, NUMBER2
    CMP AL, BL
    JL LESS
    JGE GREATEREQUAL
    
LESS: ;IF AL IS LESS THAN BL THEN MOVE AL TO CL AND RES (MEMORY LOCATION)
MOV CL, AL
MOV RES, AL
JMP END_PROGRAM 

GREATEREQUAL: ;IF AL IS GREATER THAN OR EQUAL TO BL, THEN MOVE BL TO CL AND RES (MMEORY LOCATION)
MOV CL, BL
MOV RES, BL
 


END_PROGRAM:
    MOV AH, 4CH
    INT 21H