;Q7. Write a program to add n numbers in an array.


.DATA
ARR DW 1,2,3,4,5,6,7,8,9,10; 10 NUMBERS



.CODE
START:
    MOV AX, DATA
    MOV DS, AX
    XOR AX, AX
    MOV CX, 10 ; HOW MANY ELEMENTS IN THE ARRAY
    LEA BX, ARR ;LOAD OFFSET / EFFECTIVE ADDRESS OF THE ARRAY
    
L1: 
    ADD AX, WORD PTR[BX] ;ADDING 10 NUMBERS TO AX WHERE THE PTR STANDS FOR POINTER
    ADD BX, 2 ;MOVE THE CURSOR TO THE NEXT NUMBER
    DEC CX ;DECREMENT CX BY 1
    JNZ L1 ;REPEAT UNTIL ALL NUMBERS ARE ADDED



END START