.DATA
DATA1 DB +96
DATA2 DB +80
RESULT DW ?

.CODE
START:
    MOV AX, DATA
    MOV DS, AX
    XOR AX, AX
    MOV AL, DATA1
    MOV BL, DATA2
    ADD AL, BL
    JNO OVER ;JUMP IF THERE IS NO OVERFLOW OR OF = 0
    
    MOV AL, DATA2
    CBW ;CONVERT SIGNED BYTE TO SIGNED WORD 
    MOV BX, AX
    
    MOV AL, DATA1
    CBW  ;THE RESULT IS STORED IN AX
    ADD AX, BX
    
    
OVER:
MOV RESULT, AX
END START