; ASSUMING THAT THERE IS A SPELLING ERROR OF 'EUROPE' IN AN ELECTRONIC DICTIONARY AND A USER TYPES IN 
; 'EUOROPE', WRITE A PROGRAM THAT COMPARES THESE TWO AND DISPLAYS THE FOLLOWING MESSAGE, DEPENDING ON RESULT:
; 1. IF THEY ARE EQUAL, DISPLAY "THE SPELLING IS CORRECT"
; 2. IF THEY ARE NOT EQUAL DISPLAY "WRONG SPELLING"

.DATA
ACTUAL DB "EUROPE"
TYPED DB "EUROPE"
MESSAGE1 DB "THE SPELLING IS CORRECT", "$"
MESSAGE2 DB "THE SPELLING IS INCORRECT", "$"

.CODE
START:
    MOV AX, DATA
    MOV DS, AX
    MOV ES, AX
    CLD ;DIRECTIONAL FLAGE, DF, SET TO 0 FOR AUTO INCREMENT
    MOV SI, OFFSET ACTUAL
    MOV DI, OFFSET TYPED
    MOV CX, 6
    REPE CMPSB
    JE OVER ;IF BOTH MESSAGES ARE EQUAL AND ZERO FLAG = 1
    MOV DX, OFFSET MESSAGE2
    JMP DISPLAY
    
    
OVER:
    MOV DX, OFFSET MESSAGE1
    
    
DISPLAY:
    MOV AH, 09
    INT 21H
        
END START 

; FOR QUIZ REMEBER THE INSTRUCITONS ON SLIDE 19 OF POWERPOINT 10